# Generated by Django 6.0.5 on 2026-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.CharField(max_length=3, unique=True)),
                ("rates", models.JSONField()),
                ("provider", models.CharField(default="", max_length=32)),
                ("rate_date", models.CharField(default="", max_length=10)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "instant_currency_rate",
            },
        ),
        migrations.CreateModel(
            name="InstantCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "instant_cache",
            },
        ),
    ]
