"""
Django settings for engine project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP
from django.utils.translation import gettext_lazy as _

from .git_version import get_git_ref, get_git_sha

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['localhost', '127.0.0.1']),
    CSRF_TRUSTED_ORIGINS=(list, []),
    BRAVE_API_KEY=(str, ''),
    BRAVE_SUGGEST_API_KEY=(str, ''),
    MOJEEK_API_KEY=(str, ''),
    MARGINALIA_API_KEY=(str, ''),
    STAAN_API_KEY=(str, ''),
    THETVDB_API_KEY=(str, ''),
    THETVDB_PIN=(str, ''),
    TRIPADVISOR_API_KEY=(str, ''),
    STACKEXCHANGE_API_KEY=(str, ''),
    PIXABAY_API_KEY=(str, ''),
    WORLDNEWS_API_KEY=(str, ''),
    LIBRETRANSLATE_URL=(str, ''),
    LIBRETRANSLATE_API_KEY=(str, ''),
    LIBRETRANSLATE_ORIGIN_COUNTRY=(str, 'fr'),
    PAID_PROVIDERS=(list, None),
    FOOTER_LINKS=(dict, {}),
    SOURCE_URL=(str, 'https://github.com/seurch-eu/seurch'),
    LOG_LEVEL=(str, 'INFO'),
    EMAIL_BACKEND=(str, 'django.core.mail.backends.console.EmailBackend'),
    EMAIL_HOST=(str, 'localhost'),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_HOST_USER=(str, ''),
    EMAIL_HOST_PASSWORD=(str, ''),
    DEFAULT_FROM_EMAIL=(str, 'noreply@seurch.eu'),
    API_THROTTLE_BURST=(str, '60/min'),
    API_THROTTLE_SUSTAINED=(str, '5000/day'),
    PUBLIC_API_ENABLED=(bool, True),
    STATUS_PAGE_ENABLED=(bool, True),
    STATUS_MONITOR_ENABLED=(bool, True),
    STATUS_MONITOR_TOKEN=(str, ''),
    STATUS_MONITOR_PROVIDERS=(list, []),
    LOGIN_THROTTLE_LIMIT=(int, 5),
    LOGIN_THROTTLE_WINDOW=(int, 900),
    PASSWORD_RESET_THROTTLE_LIMIT=(int, 5),
    PASSWORD_RESET_THROTTLE_WINDOW=(int, 3600),
    OPENSEARCH_THROTTLE_LIMIT=(int, 60),
    OPENSEARCH_THROTTLE_WINDOW=(int, 60),
)

environ.Env.read_env(BASE_DIR / '.env')

DEBUG = env('DEBUG')

SECRET_KEY = env('SECRET_KEY', default=None)
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-do-not-use-in-production'
    else:
        raise ImproperlyConfigured(
            'The SECRET_KEY environment variable is required when DEBUG is False.'
        )

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

CSRF_TRUSTED_ORIGINS = env('CSRF_TRUSTED_ORIGINS')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31_536_000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

SECURE_CSP_REPORT_ONLY = {
    'default-src': [CSP.SELF],
    'script-src': [CSP.SELF, CSP.NONCE],
    'style-src': [CSP.SELF, CSP.UNSAFE_INLINE],
    'img-src': [CSP.SELF, 'https:', 'data:'],
    'connect-src': [CSP.SELF],
    'object-src': [CSP.NONE],
    'frame-ancestors': [CSP.NONE],
    'base-uri': [CSP.SELF],
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'search',
    'instant',
    'web',
    'images',
    'news',
    'videos',
    'maps',
    'cards',
    'translate',
    'api',
]

MIDDLEWARE = [
    # Answers the proxy health check (/up) before host validation runs
    'config.middleware.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Stamps the CSP headers configured above (and mints the per-request
    # nonce the inline scripts use).
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    # WhiteNoise serves collected static files straight from gunicorn (no
    # separate web server needed). Must sit right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'search.middleware.AutoSyncSettingsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.csp',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'search.context_processors.theme',
                'search.context_processors.custom_bangs',
                'search.context_processors.footer_links',
                'search.context_processors.feature_flags',
                'search.context_processors.version',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db(
        'DATABASE_URL',
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
    )
}

# Shared cache, backing the brute-force/rate-limit counters (accounts.ratelimit)
# and DRF's API throttles. A database cache by default so the counters are
# shared across gunicorn workers and survive restarts; a per-process cache
# would let an attacker multiply every limit by the worker count. The table is
# created by `manage.py createcachetable` (run by bin/docker-entrypoint and
# `make migrate`). Point CACHE_URL at Redis (rediscache://...) to move it
# off the database.
CACHES = {
    'default': env.cache('CACHE_URL', default='dbcache://django_cache'),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
    ('de', _('German')),
    ('es', _('Spanish')),
    ('it', _('Italian')),
    ('pt', _('Portuguese')),
    ('nl', _('Dutch')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Dev/test serve static files straight from the finders, so no manifest is
# required. Production swaps in WhiteNoise's hashed+compressed storage below.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

if not DEBUG:
    # Compress and hash collected static files (far-future caching) and serve
    # them directly from the app container via WhiteNoise. Requires a manifest
    # built by `collectstatic`, which the Docker image does at build time.
    STORAGES['staticfiles']['BACKEND'] = (
        'whitenoise.storage.CompressedManifestStaticFilesStorage'
    )

BRAVE_API_KEY = env('BRAVE_API_KEY')
BRAVE_SUGGEST_API_KEY = env('BRAVE_SUGGEST_API_KEY')
MOJEEK_API_KEY = env('MOJEEK_API_KEY')
MARGINALIA_API_KEY = env('MARGINALIA_API_KEY')
STAAN_API_KEY = env('STAAN_API_KEY')
THETVDB_API_KEY = env('THETVDB_API_KEY')
THETVDB_PIN = env('THETVDB_PIN')
TRIPADVISOR_API_KEY = env('TRIPADVISOR_API_KEY')
STACKEXCHANGE_API_KEY = env('STACKEXCHANGE_API_KEY')
PIXABAY_API_KEY = env('PIXABAY_API_KEY')
WORLDNEWS_API_KEY = env('WORLDNEWS_API_KEY')
LIBRETRANSLATE_URL = env('LIBRETRANSLATE_URL')
LIBRETRANSLATE_API_KEY = env('LIBRETRANSLATE_API_KEY')
LIBRETRANSLATE_ORIGIN_COUNTRY = env('LIBRETRANSLATE_ORIGIN_COUNTRY')

PAID_PROVIDERS = env.list('PAID_PROVIDERS')

FOOTER_LINKS = env.dict('FOOTER_LINKS')

SOURCE_URL = env('SOURCE_URL')

GIT_REF = env('GIT_REF', default='') or get_git_ref(BASE_DIR)
GIT_SHA = env('GIT_SHA', default='') or get_git_sha(BASE_DIR)

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Email configuration
# In development the console backend prints emails to stdout.
# For production set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# and configure the SMTP variables below.
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

PASSWORD_RESET_TIMEOUT = 3600

LOGIN_THROTTLE_LIMIT = env('LOGIN_THROTTLE_LIMIT')
LOGIN_THROTTLE_WINDOW = env('LOGIN_THROTTLE_WINDOW')
PASSWORD_RESET_THROTTLE_LIMIT = env('PASSWORD_RESET_THROTTLE_LIMIT')
PASSWORD_RESET_THROTTLE_WINDOW = env('PASSWORD_RESET_THROTTLE_WINDOW')
OPENSEARCH_THROTTLE_LIMIT = env('OPENSEARCH_THROTTLE_LIMIT')
OPENSEARCH_THROTTLE_WINDOW = env('OPENSEARCH_THROTTLE_WINDOW')

LOG_SEARCH_QUERIES = env.bool('LOG_SEARCH_QUERIES', default=DEBUG)

PUBLIC_API_ENABLED = env('PUBLIC_API_ENABLED')

STATUS_PAGE_ENABLED = env('STATUS_PAGE_ENABLED')

STATUS_MONITOR_ENABLED = env('STATUS_MONITOR_ENABLED')
STATUS_MONITOR_TOKEN = env('STATUS_MONITOR_TOKEN')
STATUS_MONITOR_PROVIDERS = env('STATUS_MONITOR_PROVIDERS')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.ApiKeyAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttling.BurstRateThrottle',
        'api.throttling.SustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst': env('API_THROTTLE_BURST'),
        'sustained': env('API_THROTTLE_SUSTAINED'),
    },
    # JSON is the only representation in production; the browsable API is a
    # developer convenience kept to DEBUG so it never ships static/templates or
    # an HTML attack surface to production.
    'DEFAULT_RENDERER_CLASSES': (
        [
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
        ]
        if DEBUG
        else ['rest_framework.renderers.JSONRenderer']
    ),
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': env('LOG_LEVEL'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'search': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'instant': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'web': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'images': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'news': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'videos': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'maps': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'cards': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
        'translate': {
            'handlers': ['console'],
            'level': env('LOG_LEVEL'),
            'propagate': False,
        },
    },
}
