# Generated by Django 6.0.5 on 2026-06-11 13:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxiedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "search_proxied_image",
            },
        ),
    ]
