# Generated by Django 6.0.5 on 2026-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_searchcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=40, unique=True)),
                ("ok", models.BooleanField(default=True)),
                ("source", models.CharField(default="query", max_length=16)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("last_ok_at", models.DateTimeField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_provider_status",
            },
        ),
    ]
