# Generated by Django 6.0.6 on 2026-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0006_providerstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxiedimage",
            name="content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proxiedimage",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="proxiedimage",
            name="persist",
            field=models.BooleanField(default=False),
        ),
    ]
